---
title: "git_01"
author: "Cyann Arevalo"
date: "September 8, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
  They sought it with thimbles, they sought it with care;  
           They pursued it with forks and hope;  
  They threatened its life with a railway-share;  
            They charmed it with smiles and soap.  
  
  They shuddered to think that the chase might fail, 
 
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
  He is that fallen lance that lies as hurled,  
  That lies unlifted now, come dew, come rust,  
  But still lies pointed as it plowed the dust.  
  If we who sight along it round the world,  
  See nothing worthy to have been its mark,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
  The sun was shining on the sea,  
  Shining with all his might:  
  He did his very best to make   
  The billows smooth and bright--  
  And this was odd, because it was   
  The middle of the night.  
  
  The moon was shining sulkily,   
  Because she thought the sun   
  Had got no business to be there  
  After the day was done--   
  "It's very rude of him," she said,  
  "To come and spoil the fun!"  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
  
  Some say the world will end in fire,  
  Some say in ice.  
  From what I’ve tasted of desire  
  I hold with those who favor fire.  
  But if it had to perish twice,  
  I think I know enough of hate  
  To say that for destruction ice  
  Is also great  
  and would suffice.  
